apiVersion: apps/v1
kind: Deployment
metadata:
    name: project-deployment
    labels:
        app: project-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: project-app
    template:
        metadata:
            labels:
                app: project-app
        spec:
            containers:
                - name: container-app
                  image: anaega/project-app-image:1a1dbb4ce8fe6c68959fa3ef726849e27033699e
                  ports:
                      - containerPort: 8080
